# Generated by Django 4.2.1 on 2023-06-09 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_myuser_is_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='username',
            field=models.CharField(default='th3gr3atd3str', max_length=50, unique=True),
            preserve_default=False,
        ),
    ]
