# Generated by Django 4.2.1 on 2023-06-09 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_myuser_username'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='myuser',
            managers=[
            ],
        ),
    ]
