# Generated by Django 4.2.1 on 2023-06-17 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_myuser_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='is_authenticated',
            field=models.BooleanField(default=0),
        ),
    ]
